export type {
  ScenePrototypeDoc,
  NodePrototypeDoc,
  MeshNodePrototypeDoc,
  LightNodePrototypeDoc,
  CameraNodePrototypeDoc,
  UICanvasNodePrototypeDoc,
  UIWidgetPrototypeDoc,
  UIAnchorFieldsDoc,
  UIImageNodePrototypeDoc,
  UITextNodePrototypeDoc,
  UIButtonNodePrototypeDoc,
  UILayoutNodePrototypeDoc,
  TransformPrototypeDoc,
  PrototypeTypeMap,
  PrototypeDocumentation,
  UIScaleModeDoc,
} from "./PrototypeDocumentation";
