// ---------------------------------------------------------------------------
// web 运行时自动编译管线（单一事实源 → 双目标编译的"运行时目标"）：
//   源   = src/runtime/**（播放侧胶水，复用 src/framework/** 引擎逻辑）
//   产物 = public/engine/**（稳定路径，player.mjs / 预览 / 4 种导出模式零改动）
// 产物带 AUTO-GENERATED 头并入库（可 review、干净检出即可服务）。
//
// 关键决策：
// - three 外部化：'three' / 'three/webgpu' 解析到 public/engine/core/ 的 three
//   构建（绝对路径 + external:'relative'），Rollup 自动按各产物文件深度写相对
//   说明符（../../core/...）——CDN 模式的 Rust 说明符重写机制零改动继续成立；
// - 单文件产物（inlineDynamicImports）：试点模块自包含，不向 public/engine 散落
//   chunk；未来多模块共享框架代码时再评估 preserveModules / 公共 chunk 拆分；
// - 关闭 Vite minify：发布压缩仍由 Rust minifier 统一负责（与手写镜像时代一致，
//   且 *.min.* 之外一律过一遍保守压缩）；
// - DRACOLoader（npm 源）模块顶层的 new URL(..., import.meta.url) 在构建期补丁为
//   字符串占位：这些常量只作构造函数缺省 decoderPaths（运行时恒经 setDecoderPath
//   覆盖），而单页导出会把模块内联为 blob（import.meta.url 相对解析抛 Invalid
//   URL）。补丁未命中显式失败，避免静默产出带病文件。
//
// 用法：node scripts/build-runtime.mjs（package.json build 链第一步；
//       dev 由 vite.config.ts 的 runtimeBuildPlugin 调 buildRuntime() 自动重建）
// ---------------------------------------------------------------------------
import { build } from "vite";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ENGINE_DIR = path.join(ROOT, "public", "engine");
const CORE_DIR = path.join(ENGINE_DIR, "core");
const RUNTIME_SRC = path.join(ROOT, "src", "runtime");

const BANNER =
  "// AUTO-GENERATED by scripts/build-runtime.mjs (source: src/runtime/**) — DO NOT EDIT.\n";

/** 加载器（three npm 源）模块级 new URL 补丁：值仅作缺省路径占位。
 *  单页导出会把模块内联为 blob（import.meta.url 相对解析抛 Invalid URL），
 *  而缺省路径运行时恒经 setDecoderPath/setTranscoderPath 覆盖、永不取数。 */
const MODULE_NEW_URL_PATCHES = [
  {
    match: "/examples/jsm/loaders/DRACOLoader.js",
    patches: [
      [
        "const WASM_BIN_URL = new URL( '../libs/draco/draco_decoder.wasm', import.meta.url ).toString();",
        "const WASM_BIN_URL = '../libs/draco/draco_decoder.wasm';",
      ],
      [
        "const WASM_JS_URL = new URL( '../libs/draco/draco_wasm_wrapper.js', import.meta.url ).toString();",
        "const WASM_JS_URL = '../libs/draco/draco_wasm_wrapper.js';",
      ],
      [
        "const JS_URL = new URL( '../libs/draco/draco_decoder.js', import.meta.url ).toString();",
        "const JS_URL = '../libs/draco/draco_decoder.js';",
      ],
      [
        "js: new URL( '../libs/draco/gltf/draco_wasm_wrapper.js', import.meta.url ).toString(),",
        "js: '../libs/draco/gltf/draco_wasm_wrapper.js',",
      ],
      [
        "wasm: new URL( '../libs/draco/gltf/draco_decoder.wasm', import.meta.url ).toString(),",
        "wasm: '../libs/draco/gltf/draco_decoder.wasm',",
      ],
    ],
  },
  {
    match: "/examples/jsm/loaders/KTX2Loader.js",
    patches: [
      [
        "const WASM_BIN_URL = new URL( '../libs/basis/basis_transcoder.wasm', import.meta.url ).toString();",
        "const WASM_BIN_URL = '../libs/basis/basis_transcoder.wasm';",
      ],
      [
        "const WASM_JS_URL = new URL( '../libs/basis/basis_transcoder.js', import.meta.url ).toString();",
        "const WASM_JS_URL = '../libs/basis/basis_transcoder.js';",
      ],
    ],
  },
];

/** DRACOLoader 顶层 new URL 补丁（enforce:pre，先于 Vite 的资产 URL 变换） */
function patchDracoLoaderPlugin() {
  return {
    name: "tve-runtime-module-newurl-patch",
    enforce: "pre",
    transform(code, id) {
      const norm = id.split(path.sep).join("/");
      const target = MODULE_NEW_URL_PATCHES.find((p) => norm.includes(p.match));
      if (!target) return null;
      let out = code;
      for (const [find, replace] of target.patches) {
        if (!out.includes(find)) {
          throw new Error(`[build-runtime] 补丁未命中（three 上游已变化）: ${target.match} → ${find}`);
        }
        out = out.replace(find, replace);
      }
      return { code: out, map: null };
    },
  };
}

/** three 外部化：解析到 engine/core 的 three 构建并保持外部相对引用 */
function threeExternalPlugin() {
  return {
    name: "tve-runtime-three-external",
    enforce: "pre",
    resolveId(id) {
      if (id === "three") {
        return { id: path.join(CORE_DIR, "three.module.min.js"), external: "relative" };
      }
      if (id === "three/webgpu") {
        return { id: path.join(CORE_DIR, "three.webgpu.min.js"), external: "relative" };
      }
      return null;
    },
  };
}

/** DRACOLoader 顶层 new URL 补丁（enforce:pre，先于 Vite 的资产 URL 变换） */

/** 递归收集 src/runtime 下的入口（每个 .ts 文件 = public/engine/runtime/** 同名 .mjs；
 *  键 = 产物内相对路径（不含扩展名），如 "runtime/loaders/compressed"） */
function collectInputs() {
  const input = {};
  (function walk(dir, rel) {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const abs = path.join(dir, e.name);
      const relName = rel ? `${rel}/${e.name}` : e.name;
      if (e.isDirectory()) walk(abs, relName);
      else if (e.name.endsWith(".ts")) {
        input[`runtime/${relName.replace(/\.ts$/, "")}`] = abs;
      }
    }
  })(RUNTIME_SRC, "");
  if (!Object.keys(input).length) throw new Error("[build-runtime] src/runtime 下没有入口");
  return input;
}

/** 产物自检：相对 three 说明符存在、无 import.meta.url 残留（单页内联 blob 安全） */
function verifyOutput(input) {
  for (const name of Object.keys(input)) {
    const file = path.join(ENGINE_DIR, `${name}.mjs`);
    if (!fs.existsSync(file)) throw new Error(`[build-runtime] 产物缺失: ${file}`);
    const text = fs.readFileSync(file, "utf8");
    if (text.includes("import.meta.url")) {
      throw new Error(`[build-runtime] 产物残留 import.meta.url（单页内联 blob 下会抛 Invalid URL）: ${file}`);
    }
    if (!/from\s+["'](\.\.\/)+core\/three(\.module\.min|\.webgpu\.min)?\.js["']/.test(text)) {
      throw new Error(`[build-runtime] 产物缺少 three 相对说明符（外部化失效？）: ${file}`);
    }
  }
}

/** 外部 three 说明符修正：Vite/Rollup 对绝对外部 id 的相对化基准不可控（曾产出
 *  按错误基准算出的多层向上路径），统一在后处理按「产物文件自身目录」重算。 */
function fixExternalSpecifiers(input) {
  const targets = ["three.module.min.js", "three.webgpu.min.js"];
  for (const name of Object.keys(input)) {
    const file = path.join(ENGINE_DIR, `${name}.mjs`);
    let text = fs.readFileSync(file, "utf8");
    for (const t of targets) {
      const rel = path.relative(path.dirname(file), path.join(CORE_DIR, t)).split(path.sep).join("/");
      const re = new RegExp(`(from\\s+["'])[^"']*core[/\\\\]${t.replace(/\./g, "\\.")}(["'])`, "g");
      text = text.replace(re, (_m, pre, post) => `${pre}${rel}${post}`);
    }
    fs.writeFileSync(file, text);
  }
}

/** 执行运行时编译（dev 插件与 build 链共用；并发调用串行化） */
let inFlight = null;
export function buildRuntime(why = "") {
  if (inFlight) return inFlight;
  inFlight = (async () => {
    const t0 = Date.now();
    const input = collectInputs();
    await build({
      configFile: false,
      root: ROOT,
      logLevel: "warn",
      plugins: [threeExternalPlugin(), patchDracoLoaderPlugin()],
      build: {
        // lib 模式：产物是可 import 的模块库，入口导出必须保留（app 模式会把
        // 无 HTML 消费的入口导出整体摇掉，产出空文件）
        lib: {
          entry: input,
          formats: ["es"],
          fileName: (_format, name) => `${name}.mjs`,
        },
        outDir: ENGINE_DIR,
        emptyOutDir: false, // 产物落 public/engine，绝不能清掉手写的引擎模块
        copyPublicDir: false, // outDir 在 publicDir 内部：必须禁用，否则整个 public/ 会被复制进产物目录
        minify: false,
        sourcemap: false,
        rollupOptions: {
          // 显式开启：Vite 构建默认 makeAbsoluteExternalsRelative:false（保持绝对
          // 路径），这里必须转成相对产物文件的说明符（CDN 重写/单页重写都按相对
          // 路径匹配）
          makeAbsoluteExternalsRelative: true,
          output: {
            chunkFileNames: "runtime/_chunks/[name].mjs",
            banner: BANNER,
          },
        },
      },
    });
    fixExternalSpecifiers(input);
    verifyOutput(input);
    console.log(
      `[build-runtime] web 运行时已编译（${why || "手动"}，${Date.now() - t0}ms）→ public/engine`,
    );
  })().finally(() => {
    inFlight = null;
  });
  return inFlight;
}

// 直接执行（node scripts/build-runtime.mjs）时运行
const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  buildRuntime("手动").catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
